baseurl = "https://static.grinnell.edu/blogs/McFateM"
# baseurl = "http://localhost:8081"

title = "The Grinnell College Digital Library Application Developer's Blog"
#themesDir = "../.."
#themesDir = "themes"
theme = "m10c"
paginate = 5

[params]
  author = "Mark A. McFate"
  description = "Mark's first Hugo site, a blog, at the new Static.Grinnell.edu."
  [[params.social]]
    name = "github"
    url = "https://github.com/McFateM"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  ## Red and black theme
  ## Now follows, or should, the style guide at https://www.grinnell.edu/about/offices-services/communications/brand/visual-identity
  [params.style]
    # darkestColor shows in the header/sidebar background.
    darkestColor = "#DA291C"
    # darkColor is the page/content background.
    darkColor = "#000000"
    primaryColor = "#ffffff"
    # lightColor is used with the params.description in the header/sidebar as well as text in the body
    lightColor = "#FBEED8"
    lightestColor = "#d3d3d3"


## Everything below is from the OLD theme!
#
# languageCode = "en-us"
# title = "Grinnell College Digital Library Application Developer's Blog"
# # Define how many pages appear per site
# paginate = 5
# # Enable comments powered by Disqus by entering your disqus shortname
# #disqusShortname = "spf13"
# # Enable gogle analytics by entering your tracking code
# googleAnalytics = ""
# theme = "hugo-theme-m10c"
#
# [params]
#   site_rev = "1.5"
#   site_author = "Mark A. McFate"
#   site_author_email = "digital@grinnell.edu"
#   site_description = "Mark's first Hugo site, a blog, at the new Static.Grinnell.edu."
#   location = "Grinnell College Libraries"
#   # Link custom assets relative to /static
#   avatar = "img/GCwithLaurelLeaves.jpg"
#   header_background = "img/gc-banner.png"
#   header_title = "The Digital Library Application Developer's Blog"
#   copyright = "The views and opinions expressed on individual web pages are strictly those of their authors and are not official statements of Grinnell College."
#   custom_css = ["css/custom.css"]
#   custom_js  = ["js/search.js"]
#
#   # Enable gogle analytics by entering your tracking code
#   google_analytics = ""
#
#   sectionPagesMenu = "main"
#
# [social]
#   # Add your social network accounts to the profile section on the left
#   # by entering your username. The links to your account will be
#   # create automatically.
#   twitter   = "SummittDweller"
#   facebook  = "mark@tamatoledo.net"
#   linkedin  = "mark@tamatoledo.net"
#   behance   = ""
#   dribbble  = ""
#   instagram = ""
#   github    = "McFateM"
#   gplus     = ""
#
# [outputs]
#   # Added 19-May-2019 per https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae
#   home = ["HTML", "RSS", "JSON"]
