baseurl = "https://static.grinnell.edu/blogs/McFateM"
# baseurl = "http://localhost:8081"
languageCode = "en-us"
title = "Mark's Blog @ Static.Grinnell.edu"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Mark A. McFate"
    site_description = "Mark's first Hugo site, a blog, at the new Static.Grinnell.edu."
    location = "Grinnell College Libraries"
    # Link custom assets relative to /static
    avatar = "img/GCwithLaurelLeaves.jpg"
    header_background = "img/gc-banner.png"
    header_title = "The Digital Library Application Developer's Blog"
    copyright = "The views and opinions expressed on individual web pages are strictly those of their authors and are not official statements of Grinnell College."
    custom_css = ["css/custom.css"]
    custom_js  = ["js/search.js"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

    sectionPagesMenu = "main"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "SummittDweller"
    facebook  = "mark@tamatoledo.net"
    linkedin  = "mark@tamatoledo.net"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "McFateM"
    gplus     = ""

[outputs]
    # Added 19-May-2019 per https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae
    home = ["HTML", "RSS", "JSON"]
