baseURL = "https://static.grinnell.edu/blogs/McFateM/"
# baseURL = "http://localhost:8081"

title = "The Grinnell College Digital Library Application Developer's Blog"
#themesDir = "../.."
themesDir = "themes"
theme = ["hugo-search-fuse-js", "hugo-theme-m10c"]
paginate = 10
summaryLength = 80    # default is 70 words
googleAnalytics = "UA-131150861-2"
disqusShortname = "digital-library-applications-developer-blog"
canonifyURLs = true

enableEmoji = true
enableGitInfo = true  # makes Lastmod equivalent to git commit date

#[frontmatter]
#date = ["date", "publishDate", "lastmod"]
#lastmod = [":git", "lastmod", "date", "publishDate"]

## Config settings for the new, default "Goldmark" markdown engine
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    hrefTargetBlank = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

#relativeURLs = "true"

[params]
  build = 314
  buildDate = '2020-07-18 18:31'
  author = "Mark A. McFate"
  author_email = "digital@grinnell.edu"
  location = "Grinnell College Libraries"
  description = "Mark's first Hugo site, a blog, at the new Static.Grinnell.edu."
  copyright = "The views and opinions expressed on this site belong solely to the original author(s) and do not necessarily represent or reflect those of Grinnell College."

  [[params.social]]
    name = "github"
    url = "https://github.com/McFateM"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  ## Red and black theme
  ## Now follows, or should, the style guide at https://www.grinnell.edu/about/offices-services/communications/brand/visual-identity
  [params.style]
    # darkestColor shows in the header/sidebar background.
    darkestColor = "#DA291C"
    # darkColor is the page/content background.
    darkColor = "#000000"
    primaryColor = "#ffffff"
    # lightColor is used with text in the body
    lightColor = "#FBEED8;"
    lightestColor = "#d3d3d3"

[menu]

[[menu.main]]
  identifier = "search"
  name = "Search This Blog"
  post = "<span class='alert'>New!</span>"
  pre = "<i class='main-menu'></i>"
  url = "/search/"
  weight = -110

[[menu.main]]
  identifier = "about"
  name = "About Me"
  pre = "<i class='main-menu'></i>"
  url = "/about/"
  weight = -100

# [[menu.main]]
#   identifier = "help"
#   name = "Help"
#   pre = "<i class='main-menu'></i>"
#   url = "/help/"
#   weight = -90


## Everything below is from the OLD theme!
#
# languageCode = "en-us"
# title = "Grinnell College Digital Library Application Developer's Blog"
# # Define how many pages appear per site
# paginate = 5
# # Enable comments powered by Disqus by entering your disqus shortname
# #disqusShortname = "spf13"
# # Enable gogle analytics by entering your tracking code
# googleAnalytics = ""
# theme = "hugo-theme-m10c"
#
# [params]
#   site_rev = "1.5"
#   site_author = "Mark A. McFate"
#   site_author_email = "digital@grinnell.edu"
#   site_description = "Mark's first Hugo site, a blog, at the new Static.Grinnell.edu."
#   location = "Grinnell College Libraries"
#   # Link custom assets relative to /static
#   avatar = "img/GCwithLaurelLeaves.jpg"
#   header_background = "img/gc-banner.png"
#   header_title = "The Digital Library Application Developer's Blog"
#   copyright = "The views and opinions expressed on individual web pages are strictly those of their authors and are not official statements of Grinnell College."
#   custom_css = ["css/custom.css"]
#   custom_js  = ["js/search.js"]
#
#   # Enable gogle analytics by entering your tracking code
#   google_analytics = ""
#
#   sectionPagesMenu = "main"
#
# [social]
#   # Add your social network accounts to the profile section on the left
#   # by entering your username. The links to your account will be
#   # create automatically.
#   twitter   = "SummittDweller"
#   facebook  = "mark@tamatoledo.net"
#   linkedin  = "mark@tamatoledo.net"
#   behance   = ""
#   dribbble  = ""
#   instagram = ""
#   github    = "McFateM"
#   gplus     = ""
#
